import Head from 'next/head';
import Image from 'next/image';
import { Header } from './components/Header';

export default function MyList() {
  return (
    <>
      <Head>
        <title>My List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>My List</h1>
    </>
  );
}
